### ISSUE TITLE
  Bug Report - Missing Input Error Prompt

### ISSUE THREAD

**Issue by Deys2000** [RafaelDolores/EECS2311_GROUP5_TAB_TO_MUSICXML#1]
##  Bug Report 1/3-  Syed Quadri - Group 15
Category | Detail |
-|-
Error Name |  Missing Input Error Prompt
Error Description | Blank Tab Input does not throw Error Mentioned in User Manual
Steps to Reproduce | 1. Run Application 2. Before Inserting anything, Select Convert 
Expected Result | Error Message should pop up for Invalid Input ![image](https://user-images.githubusercontent.com/29327897/112051413-47884e00-8b28-11eb-9e58-6872fdeec545.png)
Actual Result | No error message displays, the save button remains disabled only if it was not enabled previously ![image](https://user-images.githubusercontent.com/29327897/112051546-7272a200-8b28-11eb-9c08-1c00392a89ab.png)
Machine/Version | Windows 10, Eclipse Gradle Build, Java SE 15
Priority | Low Priority, Not fatal to Operations

**Comment by mohful** [comment]
Hello Deys2000. Thank you for your bug report! This was a very good observation about the convert button, and I assure you that will be fixed in the next version (coming shortly, stay tuned). For the save button, the reason it is enabled is so that you have a chance to save it again if you cancelled it accidentally. I hope this helps!

**Comment by mohful** [comment]
The convert button has been fixed, Deys2000.
