### ISSUE TITLE
Bug Report - User interface 

### ISSUE THREAD

**Issue by Obuya** [RafaelDolores/EECS2311_GROUP5_TAB_TO_MUSICXML#22]
#### Issue description

The program allows the user to click the 'browse File' button multiple times while the file chooser prompt is still open, causing the program to open multiple prompts. 

#### Steps to reproduce the issue

1.  click on the 'Browse File' button
2. mash the  'Browse File' button :)

#### Expected result

- The program disables the  'Browse File' button while the user is currently selecting a file. 

#### Actual result

- the  'Browse File' button, once click multiple times opens multiple prompts. 

https://user-images.githubusercontent.com/52579841/112413466-a13e7300-8cf6-11eb-93a5-72ec4952962d.mp4

**Comment by mohful** [comment]
Hello Obuya. Thank you for your bug report. We always appreciate it when people take out the time to find bugs in our software so that we can make it better for users like you! I am happy to inform you that this bug has been taken into consideration and has been fixed. You will be able to see the results in the next version of our software. Again, thank you for your bug report and have a nice day!
